export default {
  '1': {day: 'Yes', night: 'No', text: 'Sunny'},
  '2': {day: 'Yes', night: 'No', text: 'Mostly Sunny'},
  '3': {day: 'Yes', night: 'No', text: 'Partly Sunny'},
  '4': {day: 'Yes', night: 'No', text: 'Intermittent Clouds'},
  '5': {day: 'Yes', night: 'No', text: 'Hazy Sunshine'},
  '6': {day: 'Yes', night: 'No', text: 'Mostly Cloudy'},
  '7': {day: 'Yes', night: 'Yes', text: 'Cloudy'},
  '8': {day: 'Yes', night: 'Yes', text: 'Dreary (Overcast)'},
  '11': {day: 'Yes', night: 'Yes', text: 'Fog'},
  '12': {day: 'Yes', night: 'Yes', text: 'Showers'},
  '13': {day: 'Yes', night: 'No', text: 'Mostly Cloudy w/ Showers'},
  '14': {day: 'Yes', night: 'No', text: 'Partly Sunny w/ Showers'},
  '15': {day: 'Yes', night: 'Yes', text: 'T-Storms'},
  '16': {day: 'Yes', night: 'No', text: 'Mostly Cloudy w/ T-Storms'},
  '17': {day: 'Yes', night: 'No', text: 'Partly Sunny w/ T-Storms'},
  '18': {day: 'Yes', night: 'Yes', text: 'Rain'},
  '19': {day: 'Yes', night: 'Yes', text: 'Flurries'},
  '20': {day: 'Yes', night: 'No', text: 'Mostly Cloudy w/ Flurries'},
  '21': {day: 'Yes', night: 'No', text: 'Partly Sunny w/ Flurries'},
  '22': {day: 'Yes', night: 'Yes', text: 'Snow'},
  '23': {day: 'Yes', night: 'No', text: 'Mostly Cloudy w/ Snow'},
  '24': {day: 'Yes', night: 'Yes', text: 'Ice'},
  '25': {day: 'Yes', night: 'Yes', text: 'Sleet'},
  '26': {day: 'Yes', night: 'Yes', text: 'Freezing Rain'},
  '29': {day: 'Yes', night: 'Yes', text: 'Rain and Snow'},
  '30': {day: 'Yes', night: 'Yes', text: 'Hot'},
  '31': {day: 'Yes', night: 'Yes', text: 'Cold'},
  '32': {day: 'Yes', night: 'Yes', text: 'Windy'},
  '33': {day: 'No', night: 'Yes', text: 'Clear'},
  '34': {day: 'No', night: 'Yes', text: 'Mostly Clear'},
  '35': {day: 'No', night: 'Yes', text: 'Partly Cloudy'},
  '36': {day: 'No', night: 'Yes', text: 'Intermittent Clouds'},
  '37': {day: 'No', night: 'Yes', text: 'Hazy Moonlight'},
  '38': {day: 'No', night: 'Yes', text: 'Mostly Cloudy'},
  '39': {day: 'No', night: 'Yes', text: 'Partly Cloudy w/ Showers'},
  '40': {day: 'No', night: 'Yes', text: 'Mostly Cloudy w/ Showers'},
  '41': {day: 'No', night: 'Yes', text: 'Partly Cloudy w/ T-Storms'},
  '42': {day: 'No', night: 'Yes', text: 'Mostly Cloudy w/ T-Storms'},
  '43': {day: 'No', night: 'Yes', text: 'Mostly Cloudy w/ Flurries'},
  '44': {day: 'No', night: 'Yes', text: 'Mostly Cloudy w/ Snow'}
};
